# This is a basic workflow to help you get started with Actions

name: Rebase workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Corresponding pull request number'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v1.3.0
        with:
          app_id: ${{ secrets.GMODNET_GITHUB_BOT_ID }}
          private_key: ${{ secrets.GMODNET_GITHUB_BOT_KEY }}
          
      - name: Configere Git User information
        run: |
             git config --global user.name "GmodNET GitHub Bot"
             git config --global user.email support@gmodnet.xyz
             
      - name: Checkout
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
             gh auth login
             gh repo clone ${{ github.repository }} ./
             gh pr checkout ${{ github.event.inputs.prNumber }}
             
      - name: Extract branch name
        uses: nelonoel/branch-name@v1.0.1
             
      - name: Rebase and push
        id: rebase_and_push
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
             git rebase ${BRANCH_NAME}
             git push --force
             
      - name: Notify if rebase was unsuccessful
        if: steps.rebase_and_push.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: gh pr comment ${{ github.event.inputs.prNumber }} --body "Automatic rebase has failed. Manual rebase is required."
