# This is a basic workflow to help you get started with Actions

name: Test 1 workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'The issue number to add a comment to'
        required: true
      commentText:
        description: 'The text of the comment to add'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get GitHub app token
        uses: tibdex/github-app-token@v1.3.0
        id: generate_token
        with:
          app_id: ${{ secrets.GMODNET_GITHUB_BOT_ID }}
          private_key: ${{ secrets.GMODNET_GITHUB_BOT_KEY }}
          
      - name: Add comment
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: gh issue comment ${{ github.event.inputs.issueNumber }} --body "${{ github.event.inputs.commentText }}"
